name: End-to-End Testing

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  e2e-oci:
    name: Publish/Verify (Container Image)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    services:
      registry:
        image: registry@sha256:860f379a011eddfab604d9acfe3cf50b2d6e958026fb0f977132b0b083b1a3d7 # 2.8.3
        ports:
          - 5000:5000
    env:
      REGISTRY: localhost:5000
      IMAGE_NAME: test
      IMAGE_TAG: latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Restart registry
        uses: docker://docker@sha256:6bb6b266d173937b4859871f556ecf8e1d822ea197f821c8b1e784452da13e55 # 24.0.7
        with:
          args: docker restart registry

      - name: Foo
        run: docker version
      - name: Build Dockerfile
        run: |
          cat <<EOF > Dockerfile
          FROM scratch
          COPY README.md .
          EOF
      - name: Build and push container image
        id: push
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Attest image
        id: attest-action
        uses: ./
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
      - name: Verify attestation
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh ext install github-early-access/gh-attestation
          gh attestation verify oci://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -R ${{ github.repository }}
